// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MIS4663_FieldProject_Group2.Data;
using MIS4663_FieldProject_Group2.Models;
using System;
using System.Collections.Generic;

namespace MIS4663_FieldProject_Group2.Data.Configurations
{
    public partial class TProjectConfiguration : IEntityTypeConfiguration<TProject>
    {
        public void Configure(EntityTypeBuilder<TProject> entity)
        {
            entity.HasKey(e => e.ProjectID).HasName("PK__TProject__761ABED0B4913DA5");

            entity.Property(e => e.ProjectConst)
            .IsRequired()
            .HasMaxLength(255)
            .IsUnicode(false);
            entity.Property(e => e.ProjectDesc)
            .IsRequired()
            .HasMaxLength(255)
            .IsUnicode(false);
            entity.Property(e => e.ProjectExp)
            .IsRequired()
            .HasMaxLength(255)
            .IsUnicode(false);
            entity.Property(e => e.ProjectStatus)
            .IsRequired()
            .HasMaxLength(255)
            .IsUnicode(false);
            entity.Property(e => e.SubmissionDate).HasColumnType("datetime");

            entity.HasOne(d => d.CompanyDesc).WithMany(p => p.TProject)
            .HasForeignKey(d => d.CompanyDescID)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK__TProject__Compan__4D94879B");

            entity.HasOne(d => d.User).WithMany(p => p.TProject)
            .HasForeignKey(d => d.UserID)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK__TProject__UserID__4CA06362");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TProject> entity);
    }
}
