// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MIS4663_FieldProject_Group2.Data;
using MIS4663_FieldProject_Group2.Models;
using System;
using System.Collections.Generic;

namespace MIS4663_FieldProject_Group2.Data.Configurations
{
    public partial class TRolesConfiguration : IEntityTypeConfiguration<TRoles>
    {
        public void Configure(EntityTypeBuilder<TRoles> entity)
        {
            entity.HasKey(e => e.RoleID).HasName("PK__TRoles__8AFACE3A766E3B2B");

            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.RoleDesc)
            .IsRequired()
            .HasMaxLength(255)
            .IsUnicode(false);
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TRoles> entity);
    }
}
