// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MIS4663_FieldProject_Group2.Data;
using MIS4663_FieldProject_Group2.Models;
using System;
using System.Collections.Generic;

namespace MIS4663_FieldProject_Group2.Data.Configurations
{
    public partial class TUsersConfiguration : IEntityTypeConfiguration<TUsers>
    {
        public void Configure(EntityTypeBuilder<TUsers> entity)
        {
            entity.HasKey(e => e.UserID).HasName("PK__TUsers__1788CCAC4BC17F54");

            entity.Property(e => e.Username)
            .IsRequired()
            .HasMaxLength(25)
            .IsUnicode(false);

            entity.HasOne(d => d.Contact).WithMany(p => p.TUsers)
            .HasForeignKey(d => d.ContactID)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK__TUsers__ContactI__49C3F6B7");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TUsers> entity);
    }
}
