// <auto-generated />
using System;
using MIS4663_FieldProject_Group2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MIS4663_FieldProject_Group2.Migrations
{
    [DbContext(typeof(DB_128040_group2Context))]
    partial class DB_128040_group2ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MIS4663_FieldProject_Group2.Models.TCompanyDescription", b =>
                {
                    b.Property<int>("CompanyDescID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyDescID"));

                    b.Property<string>("Background")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Goals")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Mission")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Structure")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("CompanyDescID")
                        .HasName("PK__TCompany__C61893BFE4461C62");

                    b.ToTable("TCompanyDescription");
                });

            modelBuilder.Entity("MIS4663_FieldProject_Group2.Models.TContact", b =>
                {
                    b.Property<int>("ContactID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactID"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ContactID")
                        .HasName("PK__TContact__5C6625BBDEDF9F99");

                    b.ToTable("TContact");
                });

            modelBuilder.Entity("MIS4663_FieldProject_Group2.Models.TPermissions", b =>
                {
                    b.Property<int>("PermissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionID"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime");

                    b.HasKey("PermissionID")
                        .HasName("PK__TPermiss__EFA6FB0FFF1B7BD4");

                    b.HasIndex("RoleID");

                    b.ToTable("TPermissions");
                });

            modelBuilder.Entity("MIS4663_FieldProject_Group2.Models.TProject", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectID"));

                    b.Property<int>("CompanyDescID")
                        .HasColumnType("int");

                    b.Property<string>("ProjectConst")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProjectDesc")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProjectExp")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProjectStatus")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ProjectID")
                        .HasName("PK__TProject__761ABED0B4913DA5");

                    b.HasIndex("CompanyDescID");

                    b.HasIndex("UserID");

                    b.ToTable("TProject");
                });

            modelBuilder.Entity("MIS4663_FieldProject_Group2.Models.TRoles", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("RoleDesc")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime");

                    b.HasKey("RoleID")
                        .HasName("PK__TRoles__8AFACE3A766E3B2B");

                    b.ToTable("TRoles");
                });

            modelBuilder.Entity("MIS4663_FieldProject_Group2.Models.TUserRole", b =>
                {
                    b.Property<int>("UserRoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserRoleID"));

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("UserRoleID")
                        .HasName("PK__TUserRol__3D978A5523FC7CCB");

                    b.HasIndex("RoleID");

                    b.HasIndex("UserID");

                    b.ToTable("TUserRole");
                });

            modelBuilder.Entity("MIS4663_FieldProject_Group2.Models.TUsers", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<int>("ContactID")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.HasKey("UserID")
                        .HasName("PK__TUsers__1788CCAC4BC17F54");

                    b.HasIndex("ContactID");

                    b.ToTable("TUsers");
                });

            modelBuilder.Entity("MIS4663_FieldProject_Group2.Models.TPermissions", b =>
                {
                    b.HasOne("MIS4663_FieldProject_Group2.Models.TRoles", "Role")
                        .WithMany("TPermissions")
                        .HasForeignKey("RoleID")
                        .IsRequired()
                        .HasConstraintName("FK__TPermissi__RoleI__5070F446");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MIS4663_FieldProject_Group2.Models.TProject", b =>
                {
                    b.HasOne("MIS4663_FieldProject_Group2.Models.TCompanyDescription", "CompanyDesc")
                        .WithMany("TProject")
                        .HasForeignKey("CompanyDescID")
                        .IsRequired()
                        .HasConstraintName("FK__TProject__Compan__4D94879B");

                    b.HasOne("MIS4663_FieldProject_Group2.Models.TUsers", "User")
                        .WithMany("TProject")
                        .HasForeignKey("UserID")
                        .IsRequired()
                        .HasConstraintName("FK__TProject__UserID__4CA06362");

                    b.Navigation("CompanyDesc");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MIS4663_FieldProject_Group2.Models.TUserRole", b =>
                {
                    b.HasOne("MIS4663_FieldProject_Group2.Models.TRoles", "Role")
                        .WithMany("TUserRole")
                        .HasForeignKey("RoleID")
                        .IsRequired()
                        .HasConstraintName("FK__TUserRole__RoleI__5441852A");

                    b.HasOne("MIS4663_FieldProject_Group2.Models.TUsers", "User")
                        .WithMany("TUserRole")
                        .HasForeignKey("UserID")
                        .IsRequired()
                        .HasConstraintName("FK__TUserRole__UserI__534D60F1");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MIS4663_FieldProject_Group2.Models.TUsers", b =>
                {
                    b.HasOne("MIS4663_FieldProject_Group2.Models.TContact", "Contact")
                        .WithMany("TUsers")
                        .HasForeignKey("ContactID")
                        .IsRequired()
                        .HasConstraintName("FK__TUsers__ContactI__49C3F6B7");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("MIS4663_FieldProject_Group2.Models.TCompanyDescription", b =>
                {
                    b.Navigation("TProject");
                });

            modelBuilder.Entity("MIS4663_FieldProject_Group2.Models.TContact", b =>
                {
                    b.Navigation("TUsers");
                });

            modelBuilder.Entity("MIS4663_FieldProject_Group2.Models.TRoles", b =>
                {
                    b.Navigation("TPermissions");

                    b.Navigation("TUserRole");
                });

            modelBuilder.Entity("MIS4663_FieldProject_Group2.Models.TUsers", b =>
                {
                    b.Navigation("TProject");

                    b.Navigation("TUserRole");
                });
#pragma warning restore 612, 618
        }
    }
}
