// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using MIS4663_FieldProject_Group2.Data.Configurations;
using MIS4663_FieldProject_Group2.Models;
using System;
using System.Collections.Generic;
#nullable disable

namespace MIS4663_FieldProject_Group2.Data;

public partial class DB_128040_group2Context : DbContext
{
    public DB_128040_group2Context()
    {
    }

    public DB_128040_group2Context(DbContextOptions<DB_128040_group2Context> options)
        : base(options)
    {
    }

    public virtual DbSet<TCompanyDescription> TCompanyDescription { get; set; }

    public virtual DbSet<TContact> TContact { get; set; }

    public virtual DbSet<TPermissions> TPermissions { get; set; }

    public virtual DbSet<TProject> TProject { get; set; }

    public virtual DbSet<TRoles> TRoles { get; set; }

    public virtual DbSet<TUserRole> TUserRole { get; set; }

    public virtual DbSet<TUsers> TUsers { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=tcp:s30.winhost.com;Initial Catalog=DB_128040_group2;Persist Security Info=True;User ID=DB_128040_group2_user;Password=LaughOutLoud#2023");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
            modelBuilder.ApplyConfiguration(new Configurations.TCompanyDescriptionConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.TContactConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.TPermissionsConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.TProjectConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.TRolesConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.TUserRoleConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.TUsersConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
