// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MIS4663_FieldProject_Group2.Models;

public partial class TCompanyDescription
{
    public int CompanyDescID { get; set; }

    public string Background { get; set; }

    public string Mission { get; set; }

    public string Structure { get; set; }

    public string Product { get; set; }

    public string Goals { get; set; }

    public virtual ICollection<TProject> TProject { get; set; } = new List<TProject>();
}