// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MIS4663_FieldProject_Group2.Models;

public partial class TContact
{
    public int ContactID { get; set; }

    public string FName { get; set; }

    public string LName { get; set; }

    public string ContactEmail { get; set; }

    public string Company { get; set; }

    public virtual ICollection<TUsers> TUsers { get; set; } = new List<TUsers>();
}