// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MIS4663_FieldProject_Group2.Models;

public partial class TPermissions
{
    public int PermissionID { get; set; }

    public int RoleID { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime UpdateDate { get; set; }

    public virtual TRoles Role { get; set; }
}