// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MIS4663_FieldProject_Group2.Models;

public partial class TProject
{
    public int ProjectID { get; set; }

    public int UserID { get; set; }

    public int CompanyDescID { get; set; }

    public string ProjectDesc { get; set; }

    public string ProjectExp { get; set; }

    public string ProjectConst { get; set; }

    public DateTime SubmissionDate { get; set; }

    public string ProjectStatus { get; set; }

    public virtual TCompanyDescription CompanyDesc { get; set; }

    public virtual TUsers User { get; set; }
}